src/Entity/Fournisseur.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\FournisseurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FournisseurRepository::class)]
#[ApiResource()]
class Fournisseur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_fournisseur = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_fournisseur = null;

    #[ORM\Column(length: 255)]
    private ?string $code_postal_fournniseur = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_fournisseur = null;

    #[ORM\Column(length: 255)]
    private ?string $ville_fournnisseur = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone_fournniseur = null;

    #[ORM\OneToMany(mappedBy: 'fournniseur', targetEntity: Fourni::class)]
    private Collection $fournis;

    public function __construct()
    {
        $this->fournis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFournisseur(): ?string
    {
        return $this->nom_fournisseur;
    }

    public function setNomFournisseur(string $nom_fournisseur): static
    {
        $this->nom_fournisseur = $nom_fournisseur;

        return $this;
    }

    public function getAdresseFournisseur(): ?string
    {
        return $this->adresse_fournisseur;
    }

    public function setAdresseFournisseur(string $adresse_fournisseur): static
    {
        $this->adresse_fournisseur = $adresse_fournisseur;

        return $this;
    }

    public function getCodePostalFournniseur(): ?string
    {
        return $this->code_postal_fournniseur;
    }

    public function setCodePostalFournniseur(string $code_postal_fournniseur): static
    {
        $this->code_postal_fournniseur = $code_postal_fournniseur;

        return $this;
    }

    public function getContactFournisseur(): ?string
    {
        return $this->contact_fournisseur;
    }

    public function setContactFournisseur(string $contact_fournisseur): static
    {
        $this->contact_fournisseur = $contact_fournisseur;

        return $this;
    }

    public function getVilleFournnisseur(): ?string
    {
        return $this->ville_fournnisseur;
    }

    public function setVilleFournnisseur(string $ville_fournnisseur): static
    {
        $this->ville_fournnisseur = $ville_fournnisseur;

        return $this;
    }

    public function getTelephoneFournniseur(): ?string
    {
        return $this->telephone_fournniseur;
    }

    public function setTelephoneFournniseur(string $telephone_fournniseur): static
    {
        $this->telephone_fournniseur = $telephone_fournniseur;

        return $this;
    }

    /**
     * @return Collection<int, Fourni>
     */
    public function getFournis(): Collection
    {
        return $this->fournis;
    }

    public function addFourni(Fourni $fourni): static
    {
        if (!$this->fournis->contains($fourni)) {
            $this->fournis->add($fourni);
            $fourni->setFournniseur($this);
        }

        return $this;
    }

    public function removeFourni(Fourni $fourni): static
    {
        if ($this->fournis->removeElement($fourni)) {
            // set the owning side to null (unless already changed)
            if ($fourni->getFournniseur() === $this) {
                $fourni->setFournniseur(null);
            }
        }

        return $this;
    }
}

src/Form/FournisseurType.php
<?php

namespace App\Form;

use App\Entity\Fournisseur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_fournisseur')
            ->add('adresse_fournisseur')
            ->add('code_postal_fournniseur')
            ->add('contact_fournisseur')
            ->add('ville_fournnisseur')
            ->add('telephone_fournniseur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fournisseur::class,
        ]);
    }
}

src/Controller/FournisseurController.php
<?php

namespace App\Controller;

use App\Entity\Fournisseur;
use App\Form\FournisseurType;
use App\Repository\FournisseurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/fournisseur')]
class FournisseurController extends AbstractController
{
    #[Route('/', name: 'app_fournisseur_index', methods: ['GET'])]
    public function index(FournisseurRepository $fournisseurRepository): Response
    {
        return $this->render('fournisseur/index.html.twig', [
            'fournisseurs' => $fournisseurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_fournisseur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $fournisseur = new Fournisseur();
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($fournisseur);
            $entityManager->flush();

            return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fournisseur/new.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fournisseur_show', methods: ['GET'])]
    public function show(Fournisseur $fournisseur): Response
    {
        return $this->render('fournisseur/show.html.twig', [
            'fournisseur' => $fournisseur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fournisseur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Fournisseur $fournisseur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fournisseur/edit.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fournisseur_delete', methods: ['POST'])]
    public function delete(Request $request, Fournisseur $fournisseur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fournisseur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($fournisseur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/fournisseur/_delete_form.html.twig
<form method="post" action="{{ path('app_fournisseur_delete', {'id': fournisseur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fournisseur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fournisseur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fournisseur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fournisseur{% endblock %}

{% block body %}
    <h1>Edit Fournisseur</h1>

    {{ include('fournisseur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_fournisseur_index') }}">back to list</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}

templates/fournisseur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fournisseur index{% endblock %}

{% block body %}
    <h1>Fournisseur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_fournisseur</th>
                <th>Adresse_fournisseur</th>
                <th>Code_postal_fournniseur</th>
                <th>Contact_fournisseur</th>
                <th>Ville_fournnisseur</th>
                <th>Telephone_fournniseur</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fournisseur in fournisseurs %}
            <tr>
                <td>{{ fournisseur.id }}</td>
                <td>{{ fournisseur.nomFournisseur }}</td>
                <td>{{ fournisseur.adresseFournisseur }}</td>
                <td>{{ fournisseur.codePostalFournniseur }}</td>
                <td>{{ fournisseur.contactFournisseur }}</td>
                <td>{{ fournisseur.villeFournnisseur }}</td>
                <td>{{ fournisseur.telephoneFournniseur }}</td>
                <td>
                    <a href="{{ path('app_fournisseur_show', {'id': fournisseur.id}) }}">show</a>
                    <a href="{{ path('app_fournisseur_edit', {'id': fournisseur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_fournisseur_new') }}">Create new</a>
{% endblock %}

templates/fournisseur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fournisseur{% endblock %}

{% block body %}
    <h1>Create new Fournisseur</h1>

    {{ include('fournisseur/_form.html.twig') }}

    <a href="{{ path('app_fournisseur_index') }}">back to list</a>
{% endblock %}

templates/fournisseur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fournisseur{% endblock %}

{% block body %}
    <h1>Fournisseur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fournisseur.id }}</td>
            </tr>
            <tr>
                <th>Nom_fournisseur</th>
                <td>{{ fournisseur.nomFournisseur }}</td>
            </tr>
            <tr>
                <th>Adresse_fournisseur</th>
                <td>{{ fournisseur.adresseFournisseur }}</td>
            </tr>
            <tr>
                <th>Code_postal_fournniseur</th>
                <td>{{ fournisseur.codePostalFournniseur }}</td>
            </tr>
            <tr>
                <th>Contact_fournisseur</th>
                <td>{{ fournisseur.contactFournisseur }}</td>
            </tr>
            <tr>
                <th>Ville_fournnisseur</th>
                <td>{{ fournisseur.villeFournnisseur }}</td>
            </tr>
            <tr>
                <th>Telephone_fournniseur</th>
                <td>{{ fournisseur.telephoneFournniseur }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_fournisseur_index') }}">back to list</a>

    <a href="{{ path('app_fournisseur_edit', {'id': fournisseur.id}) }}">edit</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}